/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import type { AiSqlProvider, MetadataStatus } from '../types';

const delay = (ms: number) =>
  new Promise(resolve => {
    setTimeout(resolve, ms);
  });

export const mockAiSqlProvider: AiSqlProvider = {
  async generateSql({ question, context, tables }) {
    await delay(300);
    const tableName = tables[0] ?? 'example_table';

    return {
      sql: [
        '-- Mock SQL generated by AutoSQL AI Assistant',
        `-- Question: ${question}`,
        `-- Database: ${context.databaseName ?? context.databaseId ?? 'unknown'}`,
        `-- Schema: ${context.schema ?? 'default'}`,
        'SELECT',
        '  *',
        `FROM ${tableName}`,
        'LIMIT 100;',
      ].join('\n'),
      tables: [tableName],
      explanation:
        'This is a placeholder response for validating the SQL Lab assistant panel.',
      warnings: ['Mock mode only. No real AutoSQL service was called.'],
      provider: 'mock',
      readonly: true,
    };
  },

  async suggestTables() {
    await delay(200);

    return {
      tables: [
        {
          name: 'example_table',
          type: 'table',
          score: 1,
          reason: 'Mock suggested table.',
          matched_columns: [{ name: 'id', type: 'integer' }],
        },
      ],
      scanned_table_count: 1,
      total_table_count: 1,
      warnings: ['Mock mode only. No real table list was loaded.'],
    };
  },

  async refreshMetadata(): Promise<MetadataStatus> {
    await delay(200);
    return {
      synced: true,
      tableCount: 2,
      indexedTableCount: 2,
      columnsUpserted: 5,
      warnings: ['Mock mode only.'],
    };
  },

  async sendFeedback(): Promise<void> {
    await delay(100);
  },
};
