/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import type { AiSqlProvider } from '../types';

const delay = (ms: number) =>
  new Promise(resolve => {
    setTimeout(resolve, ms);
  });

export const mockAiSqlProvider: AiSqlProvider = {
  async generateSql({ question, context }) {
    await delay(300);

    return {
      sql: [
        '-- Mock SQL generated by AutoSQL AI Assistant',
        `-- Question: ${question}`,
        `-- Database: ${context.databaseName ?? context.databaseId ?? 'unknown'}`,
        `-- Schema: ${context.schema ?? 'default'}`,
        'SELECT',
        '  *',
        'FROM example_table',
        'LIMIT 100;',
      ].join('\n'),
      tables: ['example_table'],
      explanation:
        'This is a placeholder response for validating the SQL Lab assistant panel.',
      warnings: ['Mock mode only. No real AutoSQL service was called.'],
    };
  },
};

