# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
import logging

from flask import request, Response
from flask_appbuilder.api import expose, permission_name, protect
from marshmallow import fields, Schema, ValidationError

from superset.extensions import event_logger
from superset.views.base_api import BaseSupersetApi, requires_json, statsd_metrics

logger = logging.getLogger(__name__)


class AiSqlGenerateSchema(Schema):
    question = fields.String(required=True)
    database_id = fields.Integer(allow_none=True)
    schema = fields.String(allow_none=True)
    current_sql = fields.String(allow_none=True)


class AiSqlRestApi(BaseSupersetApi):
    method_permission_name = {
        "generate": "read",
    }
    allow_browser_login = True
    class_permission_name = "SQLLab"
    resource_name = "ai_sql"
    openapi_spec_tag = "AI SQL"
    openapi_spec_component_schemas = (AiSqlGenerateSchema,)

    generate_schema = AiSqlGenerateSchema()

    @expose("/generate", methods=("POST",))
    @protect()
    @permission_name("read")
    @statsd_metrics
    @requires_json
    @event_logger.log_this_with_context(
        action=lambda self, *args, **kwargs: f"{self.__class__.__name__}.generate",
        log_to_statsd=False,
    )
    def generate(self) -> Response:
        """Generate SQL from a natural-language question.
        ---
        post:
          summary: Generate SQL from natural language
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AiSqlGenerateSchema'
          responses:
            200:
              description: Generated SQL result
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      result:
                        type: object
            400:
              $ref: '#/components/responses/400'
            401:
              $ref: '#/components/responses/401'
            403:
              $ref: '#/components/responses/403'
            500:
              $ref: '#/components/responses/500'
        """
        try:
            payload = self.generate_schema.load(request.json)
        except ValidationError as error:
            return self.response_400(message=error.messages)

        question = payload["question"].strip()
        if not question:
            return self.response_400(message="Question is required.")

        database_id = payload.get("database_id")
        schema = payload.get("schema") or "default"

        result = {
            "sql": "\n".join(
                [
                    "-- Mock SQL generated by AutoSQL AI Assistant",
                    f"-- Question: {question}",
                    f"-- Database ID: {database_id or 'unknown'}",
                    f"-- Schema: {schema}",
                    "SELECT",
                    "  *",
                    "FROM example_table",
                    "LIMIT 100;",
                ]
            ),
            "tables": ["example_table"],
            "explanation": (
                "This is a backend placeholder response. It validates the SQL Lab "
                "assistant API integration before AutoSQL generation is wired in."
            ),
            "warnings": ["Mock API only. No real AutoSQL service was called."],
        }
        return self.response(200, result=result)
